### ISSUE TITLE
calcul foireux des quartiles

### ISSUE THREAD

**Issue by nvuaille** [Ouack23/trucfou#1]
Yo !

Tu t'es foiré dans calcul_quartile() dans functions.php. Dans les 3 cas du switch on veut
`$median = (($low+$high)/2);`
C'est à dire que si le quartile tombe pas pile sur une valeur, on moyenne celle d'avant et celle d'après.

Ce qui me fait dire que le `if` a pas la bonne condition non plus. C'est
`if($count % 4)` pour le premier quartile
`if($count % 2)` pour le deuxième quartile
`if($count % 4)` pour le troisième quartile

**Comment by nvuaille** [comment]
J'sais pas si je suis clair en fait ...
J'ai pas de fork donc la flemme de faire une merge request et de tester mais voilà ma version : 

```
switch($int) {
    case 1:
        $val = floor(($count-1)/4);

        if($count % 4) $median = $t[$val];

        else {
            $low = $t[$val];
            $high = $t[$val+1];
            $median = (($low+$high)/2);
        }
    break;

    case 2:
        $val = floor(($count-1)/2);

        if($count % 2) $median = $t[$val];

        else {
            $low = $t[$val];
            $high = $t[$val+1];
            $median = (($low+$high)/2);
        }
    break;

    case 3:
        $val = floor(($count-1)*3/4);

        if($count % 4) $median = $t[$val];

        else {
            $low = $t[$val];
            $high = $t[$val+1];
            $median = (($low+$high)/2);
        }
    break;
```

**Comment by Ouack23** [comment]
Done plus proprement :)

47cb961
