### ISSUE TITLE
"details" button does not show details

### ISSUE THREAD

**Issue by nvuaille** [Ouack23/trucfou#15]
sad but true.

**Comment by nvuaille** [comment]
est ce que ça le fait aussi pour vous ?
Je crois que c'est de ma faute, que j'suis un pigiste qui a mis un espace dans son username =P

**Comment by Ouack23** [comment]
Non non c'est pareil chez moi !
Ca empêche pas que tu sois un pigiste tkt xD. Entre Éric et toi, sur un site qui ne gère pas les accents ... Heureusement que c'est le forum qui gère les comptes :)

**Comment by nvuaille** [comment]
fuck, ça marche en local ...

**Comment by nvuaille** [comment]
Bin j'sais pas, et je vais rien pouvoir faire avant mardi, si vous êtes chaud pour regarder d'ici là ...
(le peu que j'ai compris : on prends une 403 quand on fait la requête Ajax  )

**Comment by nvuaille** [comment]
fixed by #20
