### ISSUE TITLE
Affichage de la superficie plutot que l'état dans les détails

### ISSUE THREAD

**Issue by emilienbai** [Ouack23/trucfou#21]
https://github.com/Ouack23/trucfou/blob/f885e73f5e4b90d75578e84cfd8918c62d09ec46/include/details_functions.php#L98

c'est pas echo `'<td class="habit'.$annonce['habit'].'">'.$annonce['habit'].'</td>';`  plutôt ?

**Comment by Ouack23** [comment]
Cimer, corrigé ! 7232160
